get_apt_summary:
  target:
    device:
      integration: hostwatch
  fields:
    output_options:
      collapsed: false
      fields:
        create_notification:
          example: true
          default: true
          selector:
            boolean:
        include_raw:
          example: false
          default: false
          selector:
            boolean:
get_bootloader_summary:
  target:
    device:
      integration: hostwatch
  fields:
    output_options:
      collapsed: false
      fields:
        create_notification:
          example: true
          default: true
          selector:
            boolean:
        include_raw:
          example: false
          default: false
          selector:
            boolean:
refresh_agent_updates:
